name: simple_process
description: Run sync and async terminal processes, with some options to make it simpler to deal with different scenarios
version: 0.1.0
homepage: https://github.com/emanuel-braz/simple_process

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
